// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $auth from "./routes/auth.ts";
import * as $deauth from "./routes/deauth.ts";
import * as $index from "./routes/index.tsx";
import * as $v2 from "./routes/v2.tsx";
import * as $login from "./islands/login.tsx";
import * as $verify from "./islands/verify.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
	routes: {
		"./routes/_404.tsx": $_404,
		"./routes/_app.tsx": $_app,
		"./routes/auth.ts": $auth,
		"./routes/deauth.ts": $deauth,
		"./routes/index.tsx": $index,
		"./routes/v2.tsx": $v2,
	},
	islands: {
		"./islands/login.tsx": $login,
		"./islands/verify.tsx": $verify,
	},
	baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
