name: Deploy
on:
  push:
    branches: prod
  pull_request:
    branches: prod

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Build step
        run: |
          deno check src/main.ts
          deno lint
          deno fmt --check

      - name: Install Deno Deploy
        run: deno install -Arf jsr:@deno/deployctl

      - name: Upload to Deno Deploy
        run: deployctl deploy --p=kin-sashimi-oauth-test src/main.ts
        env:
          DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
